timeline_types = {
    "Activism" : "unemployment",
    "Administrative" : "government",
    "Advisory" : "government",
    "All Time High" : "finance",
    "Analyst Meetings" : "finance",
    "Analyst/Investor Day" : "finance",
    "Arms Deals" : "crime",
    "Auditor Changes" : "unemployment",
    "Automobiles" : "climate",
    "Bankruptcy" : "unemployment",
    "Bilateral Relations" : "government",
    "Business Activity" : "finance",
    "Business Operations" : "finance",
    "Buybacks" : "finance",
    "CEO Speeches" : "finance",
    "Capital Raises" : "unemployment",
    "Central Banks" : "unemployment",
    "Civil Conflicts" : "crime",
    "Civil Society" : "crime",
    "Climate" : "climate",
    "Company Conference Presentations" : "finance",
    "Conflicts" : "crime",
    "Consumer Credit" : "unemployment",
    "Consumer Income" : "unemployment",
    "Consumer Prices" : "unemployment",
    "Consumer Spending" : "unemployment",
    "Corporate" : "finance",
    "Cyberattacks" : "crime",
    "Cybersecurity" : "crime",
    "Debt Defaults" : "government",
    "Delayed Earnings Announcements" : "finance",
    "Delayed SEC Filings" : "finance",
    "Diplomacy" : "government",
    "Dividends" : "finance",
    "Earnings" : "finance",
    "Earnings releases" : "finance",
    "Earthquakes by Country" : "climate",
    "Econometric" : "government",
    "Economic Data" : "government",
    "Economic Outlook Reports" : "government",
    "Elections" : "government",
    "Employment" : "unemployment",
    "Enforcement" : "crime",
    "Environmental" : "climate",
    "Executive Orders" : "government",
    "Financial" : "finance",
    "Financial Crises" : "finance",
    "Financial Reporting" : "finance",
    "Fiscal Policy" : "government",
    "Fixed Income Issuance Announcements by Company" : "finance",
    "Fixed Income Issuance Closings by Company" : "finance",
    "Foreign Visits" : "government",
    "GDP" : "government",
    "Geopolitical" : "immigration",
    "Government" : "government",
    "Health" : "government",
    "Home Prices" : "unemployment",
    "Home Sales" : "unemployment",
    "Housing" : "unemployment",
    "Impeachments" : "government",
    "Index Operations" : "finance",
    "International Conflicts" : "immigration",
    "Investor Actions" : "finance",
    "Investor Activism" : "finance",
    "Leadership" : "government",
    "Legislative" : "government",
    "Macroeconomic" : "government",
    "Manufacturing" : "finance",
    "Market" : "finance",
    "Market Calendar" : "finance",
    "Military" : "government",
    "Monetary" : "government",
    "Monetary Policy Reports" : "government",
    "Money Supply" : "government",
    "Money Supply Reports" : "government",
    "Natural Disasters" : "climate",
    "Natural Gas" : "climate",
    "Natural Resources" : "climate",
    "New Homes" : "unemployment",
    "Oil" : "climate",
    "Ownership Filings" : "finance",
    "Person ends a specified role by company" : "unemployment",
    "Person ends any role by company" : "unemployment",
    "Person starts a specified role by company" : "unemployment",
    "Person starts any role by company" : "unemployment",
    "Political Actions" : "government",
    "Political Parties" : "government",
    "Political Scandals" : "government",
    "Political Scandals" : "government",
    "Political Speeches" : "government",
    "Political Violence" : "government",
    "Prices" : "finance",
    "Producer Prices" : "finance",
    "Product Announcements" : "finance",
    "Product Developments" : "finance",
    "Productivity" : "unemployment",
    "Protests" : "unemployment",
    "Referendums" : "government",
    "Regulations" : "crime",
    "Regulatory Agency Inquiries" : "finance",
    "Regulatory Authority - Regulations" : "finance",
    "Resignations" : "finance",
    "Retail" : "finance",
    "Sales/Trading Statement Release Date" : "finance",
    "Sanctions" : "government",
    "Security" : "immigration",
    "Security" : "immigration",
    "Settlements" : "immigration",
    "Shareholder Meetings" : "finance",
    "Shareholder/Analyst Calls" :  "finance",
    "Sovereign Debt" : "government",
    "Sovereign Debt Defaults" : "government",
    "Special/Extraordinary Shareholders Meeting" : "finance",
    "Speeches by Organization and Company" : "finance",
    "Sponsorships" : "finance",
    "Stock Splits" : "finance",
    "Terms" : "finance",
    "Terms of Service" : "finance",
    "Terrorism" : "crime",
    "Ticker Changes" : "finance",
    "Trade" : "government",
    "Trade Policy" : "government",
    "Tropical Cyclone Dissipation" : "climate",
    "Tropical Cyclone Formation" : "climate",
    "Tropical Cyclone Landfall" : "climate",
    "Tropical Cyclone Landfall By Country" : "climate",
    "Weapons" : "crime",
    "Weather Events" : "climate",
    "acquisition_announcements" : "finance",
    "acquisition_announcements_country" : "finance",
}
